[2025-07-02T08:50:01.267+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T08:50:01.297+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:45:00+00:00 [queued]>
[2025-07-02T08:50:01.311+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:45:00+00:00 [queued]>
[2025-07-02T08:50:01.311+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T08:50:01.323+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-07-02 07:45:00+00:00
[2025-07-02T08:50:01.336+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T08:50:01.340+0000] {standard_task_runner.py:72} INFO - Started process 1504 to run task
[2025-07-02T08:50:01.344+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-07-02T07:45:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmp3t7rojcx']
[2025-07-02T08:50:01.345+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask run_dbt_trusted
[2025-07-02T08:50:01.441+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-07-02T07:45:00+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T08:50:01.561+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T07:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-02T07:45:00+00:00'
[2025-07-02T08:50:01.566+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T08:50:01.593+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-02T08:50:01.595+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-07-02T08:50:01.611+0000] {subprocess.py:86} INFO - Output:
[2025-07-02T08:50:01.617+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-07-02T08:50:01.617+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-07-02T08:50:04.430+0000] {subprocess.py:93} INFO - [0m08:50:04  Running with dbt=1.8.0
[2025-07-02T08:50:04.736+0000] {subprocess.py:93} INFO - [0m08:50:04  Registered adapter: postgres=1.8.2
[2025-07-02T08:50:05.063+0000] {subprocess.py:93} INFO - [0m08:50:05  Found 9 models, 10 sources, 428 macros
[2025-07-02T08:50:05.065+0000] {subprocess.py:93} INFO - [0m08:50:05
[2025-07-02T08:50:05.175+0000] {subprocess.py:93} INFO - [0m08:50:05  Concurrency: 1 threads (target='dev')
[2025-07-02T08:50:05.179+0000] {subprocess.py:93} INFO - [0m08:50:05
[2025-07-02T08:50:05.185+0000] {subprocess.py:93} INFO - [0m08:50:05  1 of 4 START sql table model driven_trusted.non_pii_data ....................... [RUN]
[2025-07-02T08:50:05.309+0000] {subprocess.py:93} INFO - [0m08:50:05  1 of 4 OK created sql table model driven_trusted.non_pii_data .................. [[32mSELECT 611[0m in 0.12s]
[2025-07-02T08:50:05.311+0000] {subprocess.py:93} INFO - [0m08:50:05  2 of 4 START sql table model driven_trusted.payment_data ....................... [RUN]
[2025-07-02T08:50:05.355+0000] {subprocess.py:93} INFO - [0m08:50:05  2 of 4 OK created sql table model driven_trusted.payment_data .................. [[32mSELECT 611[0m in 0.04s]
[2025-07-02T08:50:05.359+0000] {subprocess.py:93} INFO - [0m08:50:05  3 of 4 START sql table model driven_trusted.pii_data ........................... [RUN]
[2025-07-02T08:50:05.406+0000] {subprocess.py:93} INFO - [0m08:50:05  3 of 4 OK created sql table model driven_trusted.pii_data ...................... [[32mSELECT 611[0m in 0.04s]
[2025-07-02T08:50:05.407+0000] {subprocess.py:93} INFO - [0m08:50:05  4 of 4 START sql table model driven_trusted.technical_data ..................... [RUN]
[2025-07-02T08:50:05.446+0000] {subprocess.py:93} INFO - [0m08:50:05  4 of 4 OK created sql table model driven_trusted.technical_data ................ [[32mSELECT 611[0m in 0.04s]
[2025-07-02T08:50:05.464+0000] {subprocess.py:93} INFO - [0m08:50:05
[2025-07-02T08:50:05.464+0000] {subprocess.py:93} INFO - [0m08:50:05  Finished running 4 table models in 0 hours 0 minutes and 0.40 seconds (0.40s).
[2025-07-02T08:50:05.511+0000] {subprocess.py:93} INFO - [0m08:50:05
[2025-07-02T08:50:05.511+0000] {subprocess.py:93} INFO - [0m08:50:05  [32mCompleted successfully[0m
[2025-07-02T08:50:05.512+0000] {subprocess.py:93} INFO - [0m08:50:05
[2025-07-02T08:50:05.513+0000] {subprocess.py:93} INFO - [0m08:50:05  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-07-02T08:50:06.333+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-02T08:50:06.424+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T08:50:06.426+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=run_dbt_trusted, run_id=scheduled__2025-07-02T07:45:00+00:00, execution_date=20250702T074500, start_date=20250702T085001, end_date=20250702T085006
[2025-07-02T08:50:06.466+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-02T08:50:06.481+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-02T08:50:06.482+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
