[2025-07-02T03:30:23.515+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T03:30:23.527+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:30:18.431947+00:00 [queued]>
[2025-07-02T03:30:23.533+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:30:18.431947+00:00 [queued]>
[2025-07-02T03:30:23.533+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T03:30:23.542+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_raw_data> on 2025-07-02 03:30:18.431947+00:00
[2025-07-02T03:30:23.550+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=668) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T03:30:23.553+0000] {standard_task_runner.py:72} INFO - Started process 670 to run task
[2025-07-02T03:30:23.556+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'load_raw_data', 'manual__2025-07-02T03:30:18.431947+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpvzuhvi4x']
[2025-07-02T03:30:23.558+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask load_raw_data
[2025-07-02T03:30:23.624+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:30:18.431947+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T03:30:23.680+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='load_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T03:30:18.431947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T03:30:18.431947+00:00'
[2025-07-02T03:30:23.681+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T03:30:23.698+0000] {driven_data_pipeline.py:163} INFO - Starting data insertion from CSV to PostgreSQL...
[2025-07-02T03:30:23.786+0000] {driven_data_pipeline.py:211} INFO - Data insertion complete.
[2025-07-02T03:30:23.786+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-02T03:30:23.795+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T03:30:23.796+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=load_raw_data, run_id=manual__2025-07-02T03:30:18.431947+00:00, execution_date=20250702T033018, start_date=20250702T033023, end_date=20250702T033023
[2025-07-02T03:30:23.822+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-02T03:30:23.841+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-02T03:30:23.842+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
